### ISSUE TITLE
Meta

### ISSUE THREAD

**Issue by om26er** [xconnio/wamp.rb#1]
We need a WAMP library for Ruby, using the Sans-IO architecture. That will allow the library to be used with different programming paradigms.

https://sans-io.readthedocs.io

The specification for WAMP lives here https://wamp-proto.org/wamp_latest_ietf.html

Initial aim is to implement WAMP over WebSocket over JSON

**Comment by om26er** [comment]
## How WAMP works
On the wire-level wamp runs on top of any message based transport. WebSocket is a message based transport.

* Create a based client that connects to a websocket, it should use `wamp.2.json` as websocket subprotocol. This will tell the router that the client will do messaging using json serialization.
* The client will send a HELLO message. This may just be a simple json array
  * `[1, "realm1", {"authid": "alex", ""roles": {"caller": {}, "publisher": {}, "subscriber": {}, "callee": {}}}]`

If the server has "realm1" running, it will send a json array as response
* `[2, 9939392932, {"authid": "alex", "authrole": "anonymous"}]`

That's it, your WAMP client connected successfully.

**Comment by om26er** [comment]
## STEPS
1. Initialize a ruby project, add basic CI for linting, so that the project stays uniform
2. Choose a WebSocket library and implement basic WAMP connection establishment
3. Implement core WAMP operations
  * Call and Publish first as they are the simplest
  * Register and Subscribe afterwards
4. Implement authentication
  * CryptoSign first
  * WAMPCRA and Ticket auth later.

**Comment by rubyonrails3** [comment]
@om26er  1, 2, 3 are done, though 3 is missing unsubscribe and unregister APIs, I'm going to implement that next before I get started with authentication.

**Comment by om26er** [comment]
closing, this stuff is done and much more in wampproto.rb
